name: Ansible SSH Audit CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-ssh-audit:
    runs-on: ubuntu-latest
    services:
      podman:
        image: quay.io/containers/podman
        ports:
          - 8080:8080
        options: >-
          --name podman-service
          --privileged
          --security-opt seccomp=unconfined
          --security-opt apparmor=unconfined

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman jq
          podman --version

      - name: Install dependencies for ansible-lint
        run: |
          sudo apt-get install -y python3-pip
          pip3 install ansible-lint yamllint

      - name: Run lint checks
        run: |
          make lint

      - name: Start SSH target container
        run: |
          docker run -d --name ssh-target -p 2222:22 rastasheep/ubuntu-sshd:18.04

      - name: Wait for SSH
        run: |
          until podman exec ssh-target ping -c1 127.0.0.1; do sleep 1; done
          sleep 5  # Дать SSH-серверу запуститься

#      - name: Build container image
#        run: |
#          make build

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2222 localhost >> ~/.ssh/known_hosts

      - name: Run Ansible
        run: |
          ansible-playbook -i "localhost:2222," -u root ./ansible/playbook/ssh_audit_run.yml

#      - name: Check audit logs (JSON output)
#        run: |
#          make log-check

      - name: Upload audit logs as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ssh-audit-logs
          path: |
            $(podman logs $(IMAGE_NAME) 2>/dev/null || echo "No logs") > logs.txt
            logs.txt
          retention-days: 7