name: checks

on: [push]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#      - name: Lint ansible
#        uses: ansible/ansible-lint@main
      - name: Lint yaml
        run: make lint-yaml
  tests:
    runs-on: ubuntu-latest
    needs: [lint-check]
    services:
      docker:
        image: docker:dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Start services with Docker Compose
        run: docker compose up -d --build
      
      - name: show json
        run: docker compose logs --no-log-prefix ansible-container | tail -1 | jq .

      - name: another way see json
        run: docker exec ansible-container cat /logs/*.json