name: checks

on: [push]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#      - name: Lint ansible
#        uses: ansible/ansible-lint@main
      - name: Lint yaml
        run: make lint-yaml
  tests:
    runs-on: ubuntu-latest
    needs: [lint-check]
    services:
      docker:
        image: docker:dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Start services with Docker Compose
        run: docker compose up -d --build
      
      - name: Wait for container to finish
        run: |
          timeout 120 sh -c '
            while [ "$(docker inspect -f {{.State.Running}} ansible-container 2>/dev/null)" = "true" ]; do
              echo "Ожидание завершения ansible-container..."
              sleep 5
            done
          '
          echo "container exit with code 0"

      - name: DEBUG
        run: docker ps -a

      - name: show json
        run: docker compose logs